openapi: "3.0.0"
info:
  title: "API de Tareas"
  version: "1.0.0"
paths:
  /:
    get:
      summary: "Obtener mensaje de bienvenida"
      responses:
        '200':
          description: 'Mensaje de bienvenida'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
